<script lang="ts">
  import QrScanner from 'qr-scanner';
  import { session } from '../stores/session';
  import type { TimingSession } from '../types';
  
  let fileInput: HTMLInputElement;
  let videoElement: HTMLVideoElement;
  let qrScanner: QrScanner | null = null;
  let isScanning = false;
  let importStatus = '';
  let hasCamera = false;

  async function checkCameraSupport() {
    try {
      const hasCamera = await QrScanner.hasCamera();
      return hasCamera;
    } catch (error) {
      console.error('Error checking camera support:', error);
      return false;
    }
  }

  async function startScanning() {
    if (!videoElement || isScanning) return;
    
    try {
      qrScanner = new QrScanner(
        videoElement,
        (result) => {
          stopScanning();
          handleQRResult(result.data);
        },
        {
          highlightScanRegion: true,
          highlightCodeOutline: true,
        }
      );
      
      await qrScanner.start();
      isScanning = true;
      importStatus = 'Scanning for QR code...';
    } catch (error) {
      console.error('Error starting QR scanner:', error);
      importStatus = 'Failed to start camera';
      setTimeout(() => importStatus = '', 3000);
    }
  }

  function stopScanning() {
    if (qrScanner) {
      qrScanner.destroy();
      qrScanner = null;
    }
    isScanning = false;
  }

  function handleQRResult(data: string) {
    try {
      const sessionData = JSON.parse(data) as TimingSession;
      mergeSessionData(sessionData);
      importStatus = 'QR code imported successfully!';
    } catch (error) {
      console.error('Error parsing QR code:', error);
      importStatus = 'Invalid QR code data';
    }
    setTimeout(() => importStatus = '', 3000);
  }

  function handleFileUpload(event: Event) {
    const target = event.target as HTMLInputElement;
    const file = target.files?.[0];
    
    if (!file) return;
    
    const reader = new FileReader();
    reader.onload = (e) => {
      try {
        const data = e.target?.result as string;
        const sessionData = JSON.parse(data) as TimingSession;
        mergeSessionData(sessionData);
        importStatus = 'File imported successfully!';
      } catch (error) {
        console.error('Error parsing file:', error);
        importStatus = 'Invalid file format';
      }
      setTimeout(() => importStatus = '', 3000);
    };
    reader.readAsText(file);
  }

  function mergeSessionData(importedSession: TimingSession) {
    // Simple merge strategy: combine runners and times
    const existingRunnerNames = new Set($session.runners.map(r => r.name.toLowerCase()));
    const newRunners = importedSession.runners.filter(
      runner => !existingRunnerNames.has(runner.name.toLowerCase())
    );

    // Create a mapping of old runner IDs to new ones for imported data
    const runnerIdMapping = new Map<string, string>();
    importedSession.runners.forEach(importedRunner => {
      const existingRunner = $session.runners.find(r => 
        r.name.toLowerCase() === importedRunner.name.toLowerCase()
      );
      if (existingRunner) {
        runnerIdMapping.set(importedRunner.id, existingRunner.id);
      } else {
        const newId = crypto.randomUUID();
        runnerIdMapping.set(importedRunner.id, newId);
        newRunners.push({ ...importedRunner, id: newId });
      }
    });

    // Map imported times to correct runner IDs
    const newTimes = importedSession.times.map(time => ({
      ...time,
      runnerId: runnerIdMapping.get(time.runnerId) || time.runnerId
    }));

    // Update session with merged data
    session.update(currentSession => ({
      ...currentSession,
      runners: [...currentSession.runners, ...newRunners],
      times: [...currentSession.times, ...newTimes],
      unit: importedSession.unit || currentSession.unit,
      updated: Date.now()
    }));
  }

  // Check camera support on mount
  checkCameraSupport().then(supported => {
    hasCamera = supported;
  });

  // Cleanup on destroy
  function handleDestroy() {
    stopScanning();
  }
</script>

<svelte:window on:beforeunload={handleDestroy} />

<div class="import-container">
  <div class="header">
    <h2>Import Data</h2>
    <p>Import timing data from other devices or backup files</p>
  </div>

  <div class="import-methods">
    {#if hasCamera}
      <div class="method-card">
        <h3>📱 Scan QR Code</h3>
        <p>Scan a QR code generated by another timer device</p>
        
        {#if !isScanning}
          <button class="method-btn primary" on:click={startScanning}>
            Start Camera
          </button>
        {:else}
          <div class="scanner-container">
            <video bind:this={videoElement} class="scanner-video"></video>
            <button class="stop-btn" on:click={stopScanning}>
              Stop Scanning
            </button>
          </div>
        {/if}
      </div>
    {/if}

    <div class="method-card">
      <h3>📁 Upload File</h3>
      <p>Import timing data from a JSON backup file</p>
      
      <input 
        bind:this={fileInput}
        type="file" 
        accept=".json"
        on:change={handleFileUpload}
        class="file-input"
        id="file-upload"
      />
      <label for="file-upload" class="method-btn secondary">
        Choose File
      </label>
    </div>

    <div class="method-card">
      <h3>🔄 Manual Import</h3>
      <p>Paste JSON data directly</p>
      
      <textarea 
        placeholder="Paste JSON data here..."
        class="json-input"
        on:paste={(e) => {
          setTimeout(() => {
            try {
              const data = e.target.value;
              if (data.trim()) {
                const sessionData = JSON.parse(data);
                mergeSessionData(sessionData);
                importStatus = 'Data imported successfully!';
                e.target.value = '';
                setTimeout(() => importStatus = '', 3000);
              }
            } catch (error) {
              importStatus = 'Invalid JSON format';
              setTimeout(() => importStatus = '', 3000);
            }
          }, 100);
        }}
      ></textarea>
    </div>
  </div>

  {#if importStatus}
    <div class="status-message" class:success={importStatus.includes('success')} class:error={importStatus.includes('Failed') || importStatus.includes('Invalid')}>
      {importStatus}
    </div>
  {/if}

  <div class="info-section">
    <h4>Import Information</h4>
    <ul>
      <li>Importing will merge data with your current session</li>
      <li>Runners with the same name will be combined</li>
      <li>Existing times will be preserved</li>
      <li>New runners and times will be added</li>
    </ul>
  </div>
</div>

<style>
  .import-container {
    padding: 1rem;
    max-width: 600px;
    margin: 0 auto;
  }

  .header {
    margin-bottom: 2rem;
  }

  .header h2 {
    margin: 0 0 0.5rem 0;
    color: var(--text-primary);
  }

  .header p {
    margin: 0;
    color: var(--text-secondary);
  }

  .import-methods {
    display: grid;
    gap: 1.5rem;
    margin-bottom: 2rem;
  }

  .method-card {
    background: var(--bg-secondary);
    padding: 1.5rem;
    border-radius: 0.75rem;
    border: 1px solid var(--border);
  }

  .method-card h3 {
    margin: 0 0 0.5rem 0;
    color: var(--text-primary);
  }

  .method-card p {
    margin: 0 0 1rem 0;
    color: var(--text-secondary);
    font-size: 0.875rem;
  }

  .method-btn {
    padding: 0.875rem 1.5rem;
    border: none;
    border-radius: 0.5rem;
    font-size: 1rem;
    font-weight: 600;
    cursor: pointer;
    transition: all 0.2s ease;
    text-decoration: none;
    display: inline-block;
    text-align: center;
  }

  .method-btn.primary {
    background: var(--primary);
    color: white;
  }

  .method-btn.primary:hover {
    background: var(--primary-hover);
  }

  .method-btn.secondary {
    background: var(--bg-primary);
    color: var(--text-primary);
    border: 1px solid var(--border);
  }

  .method-btn.secondary:hover {
    background: var(--bg-hover);
  }

  .file-input {
    display: none;
  }

  .scanner-container {
    position: relative;
  }

  .scanner-video {
    width: 100%;
    max-width: 300px;
    height: auto;
    border-radius: 0.5rem;
    margin-bottom: 1rem;
  }

  .stop-btn {
    background: var(--danger);
    color: white;
    border: none;
    padding: 0.5rem 1rem;
    border-radius: 0.5rem;
    cursor: pointer;
    font-weight: 500;
  }

  .stop-btn:hover {
    background: var(--danger-hover);
  }

  .json-input {
    width: 100%;
    min-height: 120px;
    padding: 1rem;
    border: 1px solid var(--border);
    border-radius: 0.5rem;
    font-family: monospace;
    font-size: 0.875rem;
    background: var(--bg-primary);
    color: var(--text-primary);
    resize: vertical;
  }

  .json-input:focus {
    outline: none;
    border-color: var(--primary);
    box-shadow: 0 0 0 3px var(--primary-alpha);
  }

  .status-message {
    padding: 1rem;
    border-radius: 0.5rem;
    text-align: center;
    font-weight: 500;
    margin-bottom: 2rem;
  }

  .status-message.success {
    background: var(--success-bg);
    color: var(--success);
  }

  .status-message.error {
    background: var(--danger-bg);
    color: var(--danger);
  }

  .info-section {
    background: var(--bg-secondary);
    padding: 1.5rem;
    border-radius: 0.75rem;
    border: 1px solid var(--border);
  }

  .info-section h4 {
    margin: 0 0 1rem 0;
    color: var(--text-primary);
  }

  .info-section ul {
    margin: 0;
    padding-left: 1.5rem;
    color: var(--text-secondary);
  }

  .info-section li {
    margin-bottom: 0.5rem;
  }
</style>